//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP_service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voiture
    {
        public int Id { get; set; }
        public string Marque { get; set; }
        public string Modele { get; set; }
        public System.DateTime Annee { get; set; }
        public string couleur { get; set; }
        public double Puissance { get; set; }
        public string NumeroSerie { get; set; }
    }
}
